app = "demo-kcd-romania-2024"
primary_region = "ord"

[build]
  image = "ghcr.io/sagikazarmark/demo-kcd-romania-2024:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
